### ISSUE TITLE
Termine mi parte de respuesta. Continue

### ISSUE THREAD

**Issue by stefanomugetti** [stefanomugetti/TP_SO_i3_103#6]
Respondi las preguntas A y B del punto 9, continue por favor.

**Comment by Ex0num** [comment]
Yo también. Ya pushée mis respuestas. Solo queda la ultima, que le corresponde a Alfa. @valentinlaplume
Valentin fijate de ir y hacer un copy-paste de la documentación que fuimos escribiendo de los comandos. Te piden el punto 8. Por suerte ya lo tenemos documentado asique es que hagas el git pull, git branch, git checkout main (que es donde esta el archivo de respuestas). Abrí el archivo ya sea con vim o interfaz grafica, agrega tus respuestas, guarda el archivo. y git add -A, git commit -m, y porfavor el **git push al origen main ->**  git push origin main.
Ya con eso, habríamos terminado todo. 🥇  👍  💯  :-)
